services:
  spark-master:
    container_name: spark-master
    build: .
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
      - ./warehouse:/opt/spark/warehouse
    env_file:
      - .env.spark
    ports:
      - '8080:8080' # Spark master Web UI
      - '7077:7077' # For spark-node-to-spark-node queries
      - '4040:4040' # Spark worker data
      - '8889:8889' # Optionaly - Jupyter web UI

  spark-history-server:
    container_name: spark-history
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
      - ./warehouse:/opt/spark/warehouse
    ports:
      - '18080:18080'

  spark-worker:
    container_name: spark-worker
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
      - ./warehouse:/opt/spark/warehouse
  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    hostname: minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
    - "9000:9000"
    - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: dev@1234
    volumes:
      - minio-data:/data

#  namenode:
#    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
#    container_name: namenode
#    restart: always
#    ports:
#      - 9870:9870
#      - 9000:9000
#    volumes:
#      - hadoop_namenode:/hadoop/dfs/name
#    environment:
#      - CLUSTER_NAME=test
#      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
#    env_file:
#      - ./hadoop.env
#
#  datanode:
#    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
#    container_name: datanode
#    restart: always
#    volumes:
#      - hadoop_datanode:/hadoop/dfs/data
#    environment:
#      SERVICE_PRECONDITION: "namenode:9870"
#      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
#    ports:
#      - "9864:9864"
#    env_file:
#      - ./hadoop.env
volumes:
  spark-logs:
  minio-data:
#  hadoop_namenode:
#  hadoop_datanode: