version: "3"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8001:8001
    container_name: jupyter_notebook
    command: "jupyter notebook --no-browser --port=8001 --ip=0.0.0.0"
    networks:
      - notebook
networks:
  notebook: