spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions

spark.sql.catalog.demo=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.demo.type=rest

spark.sql.catalog.demo.uri=http://polaris:8181/api/catalog

spark.sql.catalog.demo.warehouse=warehouse

spark.sql.catalog.demo.credential=root:s3cr3t
spark.sql.catalog.demo.scope=PRINCIPAL_ROLE:ALL

spark.sql.catalog.demo.io-impl=org.apache.iceberg.aws.s3.S3FileIO

spark.sql.catalog.demo.s3.endpoint=http://minio:9000
spark.sql.catalog.demo.s3.path-style-access=true

spark.sql.catalog.demo.s3.access-key-id=admin
spark.sql.catalog.demo.s3.secret-access-key=dev@1234

spark.sql.defaultCatalog=demo

spark.eventLog.enabled=true
spark.eventLog.dir=/home/iceberg/spark-events
spark.history.fs.logDirectory=/home/iceberg/spark-events

spark.sql.catalogImplementation=in-memory